import { ClientInfo } from "@/types/client";

export const mockClients: ClientInfo[] = [
  {
    id: "daon-001",
    companyName: "(주) 다온기획",
    companyNameEn: "Daon Planning Co.",
    isVip: true,
    contractStatus: "계약중",
    ceo: "김다온",
    businessNumber: "123-45-67890",
    industry: "광고 / 마케팅",
    foundedAt: "2015. 03. 12",
    scale: "중소기업 · 직원 42명",
    manager: "박지운 매니저",
    phone: "010-1234-5678",
    email: "jy.park@daan.co.kr",
    address: "서울 강남구 테헤란로 123",
    registeredAt: "2023. 06. 01",
    memo: "월 정기 미팅 매월 셋째 주 수요일 · 결제일 25일",
    products: [
      { id: 1, name: "브랜드 캠페인 패키지 A", category: "서비스", unitPrice: 4500000, quantity: 1, status: "진행중" },
      { id: 2, name: "SNS 운영대행 (3개월)", category: "구독", unitPrice: 1200000, quantity: 3, status: "진행중" },
      { id: 3, name: "리플렛 인쇄 — 5천부", category: "인쇄", unitPrice: 380000, quantity: 5000, status: "완료" },
      { id: 4, name: "영상 콘텐츠 제작", category: "출력", unitPrice: 2800000, quantity: 2, status: "대기" },
    ],
    history: [
      {
        id: "h-001", date: "2026.05.02", name: "5월 캠페인 킥오프", assignee: "이준호",
        status: "진행중", note: "컨셉 시안 3종",
        detail: {
          summary: "여름 신메뉴 출시에 맞춘 통합 캠페인. 디지털 + 옥외 + 매장 POP 동시 진행.",
          requestedAt: "2026.04.28", dueDate: "2026.06.10",
          members: "디자이너 2 · 기획 1 · 카피 1",
          budget: "₩ 4,500,000 (계약 패키지 A에서 차감)",
          checkItems: [
            { id: "c1", label: "컨셉 시안 3종 제작", done: true },
            { id: "c2", label: "고객사 1차 컨펌", done: false },
            { id: "c3", label: "최종안 확정", done: false },
            { id: "c4", label: "결과물 납품", done: false },
          ],
          files: [
            { id: "f1", name: "킥오프_브리핑.pdf", type: "pdf" },
            { id: "f2", name: "컨셉시안_A.psd", type: "psd" },
            { id: "f3", name: "컨셉시안_B.psd", type: "psd" },
            { id: "f4", name: "레퍼런스보드.pdf", type: "pdf" },
          ],
        },
      },
      { id: "h-002", date: "2026.04.20", name: "리플렛 납품 완료", assignee: "박지운", status: "완료", note: "5,000부" },
      { id: "h-003", date: "2026.04.05", name: "월간 정기 미팅", assignee: "김다온", status: "완료", note: "최치독 #042" },
      { id: "h-004", date: "2026.03.15", name: "SNS 운영대행 2분기 갱신", assignee: "최수아", status: "진행중", note: "자동결제" },
      { id: "h-005", date: "2026.02.28", name: "영상 콘텐츠 1차 시안", assignee: "이준호", status: "수정요청", note: "재작업 요청" },
    ],
  },
  {
    id: "bloom-002",
    companyName: "블룸 스튜디오",
    companyNameEn: "Bloom Studio",
    isVip: false,
    contractStatus: "계약중",
    ceo: "이수현",
    businessNumber: "234-56-78901",
    industry: "디자인 / 브랜딩",
    foundedAt: "2019. 07. 01",
    scale: "소기업 · 직원 12명",
    manager: "최민재 매니저",
    phone: "010-2345-6789",
    email: "minjae@bloom.kr",
    address: "서울 마포구 홍대앞로 45",
    registeredAt: "2024. 01. 15",
    memo: "로고 리뉴얼 프로젝트 진행 중. 담당자 변경 이력 있음.",
    products: [
      { id: 1, name: "브랜드 아이덴티티 개발", category: "서비스", unitPrice: 3200000, quantity: 1, status: "진행중" },
      { id: 2, name: "명함 / 패키지 디자인", category: "인쇄", unitPrice: 850000, quantity: 1, status: "계획중" },
    ],
    history: [
      { id: "h-001", date: "2026.04.30", name: "BI 1차 시안 제출", assignee: "최민재", status: "수정요청", note: "로고 컬러 재검토" },
      { id: "h-002", date: "2026.04.10", name: "킥오프 미팅", assignee: "이수현", status: "완료", note: "" },
    ],
  },
  {
    id: "helix-003",
    companyName: "헬릭스 테크",
    companyNameEn: "Helix Tech Inc.",
    isVip: true,
    contractStatus: "계약중",
    ceo: "박준혁",
    businessNumber: "345-67-89012",
    industry: "IT / 소프트웨어",
    foundedAt: "2012. 11. 20",
    scale: "중견기업 · 직원 180명",
    manager: "김서연 매니저",
    phone: "010-3456-7890",
    email: "seoyeon.k@helix.io",
    address: "서울 성동구 성수이로 77",
    registeredAt: "2022. 03. 08",
    memo: "연간 계약. 분기별 리포트 납품 필수.",
    products: [
      { id: 1, name: "UI/UX 리뉴얼 프로젝트", category: "서비스", unitPrice: 12000000, quantity: 1, status: "진행중" },
      { id: 2, name: "앱 런칭 영상 제작", category: "출력", unitPrice: 4500000, quantity: 1, status: "대기" },
      { id: 3, name: "뉴스레터 월간 운영", category: "구독", unitPrice: 600000, quantity: 12, status: "진행중" },
    ],
    history: [
      { id: "h-001", date: "2026.05.01", name: "2분기 리포트 제출", assignee: "김서연", status: "완료", note: "Q2 리포트" },
      { id: "h-002", date: "2026.04.15", name: "UI 프로토타입 공유", assignee: "박준혁", status: "진행중", note: "피그마 링크" },
    ],
  },
  {
    id: "verde-004",
    companyName: "베르데 F&B",
    companyNameEn: "Verde F&B Co.",
    isVip: false,
    contractStatus: "협의중",
    ceo: "정하린",
    businessNumber: "456-78-90123",
    industry: "식품 / 외식",
    foundedAt: "2020. 05. 15",
    scale: "소기업 · 직원 28명",
    manager: "윤재호 매니저",
    phone: "010-4567-8901",
    email: "jaeho@verde.co.kr",
    address: "경기 성남시 분당구 판교역로 166",
    registeredAt: "2025. 09. 20",
    memo: "신규 브랜드 론칭 준비 중. 예산 협의 단계.",
    products: [
      { id: 1, name: "브랜드 패키지 기획", category: "서비스", unitPrice: 2800000, quantity: 1, status: "계획중" },
    ],
    history: [
      { id: "h-001", date: "2026.04.28", name: "제안서 발표", assignee: "윤재호", status: "진행중", note: "2차 제안 예정" },
    ],
  },
  {
    id: "nova-005",
    companyName: "노바 미디어그룹",
    companyNameEn: "Nova Media Group",
    isVip: true,
    contractStatus: "계약종료",
    ceo: "한지호",
    businessNumber: "567-89-01234",
    industry: "미디어 / 콘텐츠",
    foundedAt: "2010. 02. 28",
    scale: "대기업 · 직원 320명",
    manager: "오다빈 매니저",
    phone: "010-5678-9012",
    email: "dabin.oh@nova.media",
    address: "서울 중구 을지로 100",
    registeredAt: "2021. 05. 11",
    memo: "계약 종료. 재계약 가능성 있음 — 6월 미팅 예정.",
    products: [
      { id: 1, name: "연간 콘텐츠 플랜 운영", category: "구독", unitPrice: 8000000, quantity: 12, status: "완료" },
    ],
    history: [
      { id: "h-001", date: "2026.03.31", name: "계약 종료 확인", assignee: "오다빈", status: "완료", note: "최종 정산 완료" },
      { id: "h-002", date: "2026.02.20", name: "연간 결산 리포트 제출", assignee: "한지호", status: "완료", note: "연간 리포트" },
    ],
  },
];

export const mockClient = mockClients[0];
