import type { Metadata } from "next";
import { Plus_Jakarta_Sans } from "next/font/google";
import "@/app/globals.css";
import { cn } from "@/lib/utils";
import HomeHeader from "@/components/containers/homeHeader";

const plusJakartaSans = Plus_Jakarta_Sans({
  variable: "--font-plus-jakarta-sans",
  subsets: ["latin"],
  weight: ["300", "400", "500", "600", "700"],
});

export const metadata: Metadata = {
  title: "비전스퀘어 | VISION SQUARE ",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ko">
      <body
        className={`${cn('min-h-screen' )} ${plusJakartaSans.variable} antialiased`}
      >
        <HomeHeader />
        {children}
      </body>
    </html>
  );
}
